In [7]:
!pip install transformers
sentences = [
    "It had been sixteen days since the zombies first attacked.",
    "When confronted with a rotary dial phone the teenager was perplexed.",
    "His confidence would have been admirable if it wasn't for his stupidity.",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "They called out her name time and again, but were met with nothing but silence.",
    "After the last zombie attack sixteen days back, they are taking control of the city",
]


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 36.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.8/294.8 kB 27.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 91.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 74.3 MB/s eta 0:00:00


In [8]:
from transformers import AutoTokenizer, AutoModel
import torch


In [9]:
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-mpnet-base-v2')

In [10]:
tokens = {'input_ids': [], 'attention_mask': [] }
for sentence in sentences:
    new_tokens = tokenizer(sentence, max_length=512, truncation=True, padding='max_length', return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])
tokens['input_ids'].shape

torch.Size([6, 512])

In [11]:
outputs = model(**tokens)
outputs

BaseModelOutputWithPooling(last_hidden_state=tensor([[[-1.6771e-02,  2.7876e-02,  7.9733e-02,  ...,  8.5568e-02,
          -1.9001e-01,  3.5048e-02],
         [ 1.0377e-01,  1.3945e-01,  4.4118e-02,  ...,  1.5550e-01,
          -2.6237e-01,  2.6015e-02],
         [ 7.1797e-02,  9.0426e-02,  3.3001e-02,  ...,  9.4124e-02,
          -2.1211e-01,  2.2209e-02],
         ...,
         [-4.7747e-03,  9.3277e-02,  6.8231e-02,  ...,  2.2988e-01,
          -1.6626e-01,  1.0913e-01],
         [-4.7747e-03,  9.3277e-02,  6.8231e-02,  ...,  2.2988e-01,
          -1.6626e-01,  1.0913e-01],
         [-4.7747e-03,  9.3277e-02,  6.8231e-02,  ...,  2.2988e-01,
          -1.6626e-01,  1.0913e-01]],

        [[ 1.2549e-01, -1.0631e-01,  3.6856e-02,  ...,  6.0813e-02,
          -9.1067e-02,  3.6397e-02],
         [ 1.5688e-01, -2.4870e-01,  4.6817e-03,  ...,  8.2096e-02,
          -1.8744e-01,  7.9757e-02],
         [ 1.9245e-01, -1.4947e-01,  6.3418e-02,  ...,  1.9506e-01,
          -8.3352e-02,  5.4228e

In [21]:
embeddings = outputs.last_hidden_state
embeddings[0]

tensor([[-0.0168,  0.0279,  0.0797,  ...,  0.0856, -0.1900,  0.0350],
        [ 0.1038,  0.1395,  0.0441,  ...,  0.1555, -0.2624,  0.0260],
        [ 0.0718,  0.0904,  0.0330,  ...,  0.0941, -0.2121,  0.0222],
        ...,
        [-0.0048,  0.0933,  0.0682,  ...,  0.2299, -0.1663,  0.1091],
        [-0.0048,  0.0933,  0.0682,  ...,  0.2299, -0.1663,  0.1091],
        [-0.0048,  0.0933,  0.0682,  ...,  0.2299, -0.1663,  0.1091]],
       grad_fn=<SelectBackward0>)

In [16]:
attention_mask = tokens['attention_mask']
attention_mask[1]


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [18]:
resized_attention_mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
resized_attention_mask[1][0]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 

In [19]:
masked_embedding = embeddings * resized_attention_mask
masked_embedding.shape

torch.Size([6, 512, 768])

In [20]:
summed_masked_embeddings = torch.sum(masked_embedding, 1)
summed_masked_embeddings.shape

torch.Size([6, 768])

In [25]:
count_of_one_in_mask_tensor=resized_attention_mask.sum(1)

In [26]:
mean_pooled = summed_masked_embeddings / count_of_one_in_mask_tensor

In [28]:
from sklearn.metrics.pairwise import cosine_similarity
mean_pooled = mean_pooled.detach().numpy()
cosine_similarity([mean_pooled[0]], mean_pooled[1:])

array([[ 0.12543598,  0.06102018, -0.00801763,  0.2013635 ,  0.683272  ]],
      dtype=float32)